language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: e83d765671f1582cc506ffd7da9e457a5499ffbe
  local_dir: build
  on:
    branch: master
  env:
    process.env.CI : false
    CI : false  
